# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - petstore/petstoreautomationheadless/*

resources:
- repo: self

stages:
- stage: Build
  displayName: Build & Test Stage
  jobs: 
  - job: Automation
    displayName: Build & Execute Automated Regression Tests
    pool: 
      name: Azure Automation Pipelines
      demands:
        - agent.name -equals automation
    steps:
    - script: |
        ls -l
        cd c:/Users/chtrembl/agent/_work/1/s/petstore/petstoreautomationheadless
        mvn clean test