apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstoreservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petstoreservice
  template:
    metadata:
      labels:
        app: petstoreservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: petstoreservice
        image: azurepetstorecr.azurecr.io/petstoreservice
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 8080
        env:
          - name: PETSTORESERVICE_SERVER_PORT
            value: "8080"
          - name: spring.config.name
            value: application_with_everything_enabled
          - name: PETSTORESERVICE_AI_INSTRUMENTATION_KEY
            valueFrom:
              secretKeyRef:
                name: aisecretkey
                key: secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: petstoreservice-hpa
spec:
  maxReplicas: 12 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petstoreservice
  targetCPUUtilizationPercentage: 80 # target CPU utilization
